[theme]
name = "solarized-dark"
[theme.overrides]
info_bg = "#073642"
info_fg = "#93a1a1"
idle_bg = "#073642"
idle_fg = "#93a1a1"
good_bg = "#073642"
good_fg = "#93a1a1"
separator = " "

[icons]
name = "awesome"
[icons.overrides]
time = ""


[[block]]
block = "keyboard_layout"
driver = "kbddbus"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "networkmanager"
ap_format = "{ssid} {freq}Hz {strength}%"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "used"
unit = "Percent"
interval = 20
warning = 80.0
alert = 90.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"
chip = "*-isa-*"
good = 40
idle = 60
info = 70
warning = 90

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%b %d, %a %R"
